### ISSUE TITLE
[0.0.1-alpha] Missing Service Contract

### ISSUE THREAD

**Issue by samanthabaita** [revas/animo#6]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

**Comment by lykkechen** [comment]
I am implementing alianco. I'm having problems with the user profile. I think that animo is the right place to issue these problems: 
- I got to the part where I rendered the list of citizens but I'm missing the citizens profile picture from alianco interface;
- I miss a way to search users to be added to a realm in my autocomplete component.

What about describing a `getProfile(userHid)` to retrieve user information (such as profile picture) and a `searchUsers(filter)` to retrieve a small list of users where each user contains the filter in theirs hid?

**Comment by hashbardd** [comment]
Hi @lykkechen, actually we have to implement `getProfile()` for the full user info. We can implement a reduced `getProfile(userHid)` with the minimal user information (maybe in the future we can implement a way to control the privacy of this mechanism).

I like the idea of a `searchUsers(filter)`! 😄 Today I'm on this contract ❤️

**Comment by lykkechen** [comment]
Thanks @hashbardd, I like your idea of the reduced operation on getting the profile, remember to include the profile picture for alianco 😃
